### ISSUE TITLE
Beberapa tafsir text ????

### ISSUE THREAD

**Issue by mazipan** [rioastamal/quran-json#2]
Contoh di: https://quranweb.id/2/286/

**Comment by rioastamal** [comment]
Terima kasih. Sepertinya masalah terdapat pada project quran-text karena quran-json mengambil data dari project tersebut. 

https://github.com/rioastamal/quran-text/blob/master/tafsir/id/kemenag/2/286.txt

Melakukan pengecekan...

**Comment by rioastamal** [comment]
Daftar teks tafsir yang bermasalah.

```
tafsir/id/kemenag/61/10.txt
tafsir/id/kemenag/7/121.txt
tafsir/id/kemenag/7/122.txt
tafsir/id/kemenag/26/157.txt
tafsir/id/kemenag/26/180.txt
tafsir/id/kemenag/37/152.txt
tafsir/id/kemenag/63/5.txt
tafsir/id/kemenag/4/102.txt
tafsir/id/kemenag/40/12.txt
tafsir/id/kemenag/2/286.txt
tafsir/id/kemenag/22/1.txt
```

Perbaikan akan segera dijadwalkan.

**Comment by rioastamal** [comment]
Fixed pada commit f98ab74f4b4f7f9f0b300a9fe05cad89a77759cd. 

See also https://github.com/rioastamal/quran-json/releases
