### ISSUE TITLE
text arab

### ISSUE THREAD

**Issue by marelgunawan** [rioastamal/quran-json#5]
ada yang mengganjal pada ( hampir semua ) surah yaitu terdapat simbol  ࣖ, dan terkadang huruf ain kecil ada yg hilang. Saya memberikan contoh surah al - fatihah terdapat simbol  ࣖ dan hilangnya ain di akhir ayat ke-7 yang seharusnya ada. Ada surah lain yang semacam ini

        "text": {
            "1": "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ",
            "2": "اَلْحَمْدُ لِلّٰهِ رَبِّ الْعٰلَمِيْنَۙ",
            "3": "الرَّحْمٰنِ الرَّحِيْمِۙ",
            "4": "مٰلِكِ يَوْمِ الدِّيْنِۗ",
            "5": "اِيَّاكَ نَعْبُدُ وَاِيَّاكَ نَسْتَعِيْنُۗ",
            "6": "اِهْدِنَا الصِّرَاطَ الْمُسْتَقِيْمَ ۙ",
            "7": "صِرَاطَ الَّذِيْنَ اَنْعَمْتَ عَلَيْهِمْ ەۙ غَيْرِ الْمَغْضُوْبِ عَلَيْهِمْ وَلَا الضَّاۤلِّيْنَ ࣖ"
        }

**Comment by rioastamal** [comment]
Sepertinya itu tergantung dari font yang digunakan oleh Github. Jika anda view secara manual di Terminal maka akan terlihat simbol 'ain diakhir ayat.

Hal itu dapat dikonfirmasi jika anda membuka https://quranweb.id/1/ 
Karena sumber quranweb.id digenerate dari quran-json.

**Comment by marelgunawan** [comment]
Mungkin bisa di share, lebih baik menggunakan font apa

**Comment by rioastamal** [comment]
Bisa anda cek di project QuranWeb. https://github.com/rioastamal/quran-web/
