### ISSUE TITLE
Format Ayat

### ISSUE THREAD

**Issue by n2ng-dev** [rioastamal/quran-json#6]
Terimakasih project ini sangat membantu untuk pengembangan aplikasi,
bisakah di generator.sh nya untuk merubah format surah nya seperti gambar berikut, agar lebih mudah.

terimakasih.

![Screenshot 2020-04-07 at 13 51 34](https://user-images.githubusercontent.com/12078569/78638731-f95a4a80-78d6-11ea-8c7c-3749d8472af5.png)

**Comment by rioastamal** [comment]
Mohon maaf tetapi saya lebih prefer untuk format yang sekarang. Jika anda ingin seperti format diatas sebenarnya tidak sulit untuk merubahnya, tidak harus menggunakan Bash lewat generator.sh jika anda tidak menguasai Bash.

Anda dapat menggunakan bahasa pemrograman lain yang anda rasa familiar untuk memproses file quran-text atau bahkan dari quran-json yang sekarang untuk ditransformasikan ke format yang anda inginkan diatas.

Salam.
